#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Apple developer setup for the app's own bundle id and container.
# eczema-helper#768. Bundle id / container stem settled by #697; entitlements
# forced by #705 (mandatory sync) and #714 (everything encrypted).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

BUNDLE_ID="jirigrill.eczema"
CONTAINER_ID="iCloud.jirigrill.eczema"
DEVICE_UDID="00008130-001164190A93803A"
DEVICE_NAME="iPhone 15 Pro (iOS 26.5.2)"
DETECTED_TEAM="A4MJZ465YY"
RECORD="docs/setup/signing-and-container.md"
ENV_FILE="${ENV_FILE:-$HOME/.eczema-ios-signing.env}"

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
SECRETS_XCCONFIG="${SECRETS_XCCONFIG:-$REPO_ROOT/Config/Secrets.xcconfig}"

# write_secrets_xcconfig TEAM_ID — emit the gitignored xcconfig the local build reads.
#
# Config/Base.xcconfig ends in `#include? "Secrets.xcconfig"` and carries no Team ID,
# because this repo is public. Signing locally therefore needs this one file, and a human
# following prose to create it is a setup step this wizard is supposed to own.
write_secrets_xcconfig() {
  local team="$1"
  if ! grep -q '^Secrets\.xcconfig$' "$REPO_ROOT/.gitignore" 2>/dev/null; then
    SKIPPED+=("write $SECRETS_XCCONFIG by hand — .gitignore no longer covers it, and it must never be committed")
    warn "refusing to write Secrets.xcconfig — .gitignore does not list it"
    return
  fi
  mkdir -p "$(dirname "$SECRETS_XCCONFIG")"
  cat > "$SECRETS_XCCONFIG" <<EOF
// Written by scripts/signing-setup.sh. Gitignored — never commit this file.
// Config/Base.xcconfig includes it optionally, so CI (CODE_SIGNING_ALLOWED=NO)
// builds fine on a clean checkout without it.
DEVELOPMENT_TEAM = $team
EOF
  WRITTEN_ENV+=("DEVELOPMENT_TEAM → Config/Secrets.xcconfig")
  printf '  %s✓ wrote%s DEVELOPMENT_TEAM → %s\n' "$GREEN" "$RESET" "$SECRETS_XCCONFIG"
}

banner "Apple signing identity + CloudKit container — $BUNDLE_ID"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Confirm the team, and the identity you already have"
say "Your Mac already holds a usable development identity — nothing to mint"
say "unless you want a fresh one:"
step "Apple Development: Jiri Grill (57V7L4QL47)"
step "Team (cert OU): $DETECTED_TEAM — valid until 2027-08-17"
say ""
say "Enrolment is individual (no s.r.o. for v1), per #768."
say "If the team below is wrong, the value on the portal page wins."
open_url "https://developer.apple.com/account"
step "Sign in (2FA). The Membership details panel shows your Team ID."
ask APPLE_TEAM_ID "Team ID [detected $DETECTED_TEAM]:"
[[ -z "$APPLE_TEAM_ID" ]] && APPLE_TEAM_ID="$DETECTED_TEAM"
write_env APPLE_TEAM_ID "$APPLE_TEAM_ID"
write_secrets_xcconfig "$APPLE_TEAM_ID"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Register the physical device"
say "Registering the device by UDID makes it usable by any profile on this"
say "team, rather than only by the spike Xcode signed automatically."
say ""
step "Device: $DEVICE_NAME"
step "UDID:   $DEVICE_UDID"
say ""
open_url "https://developer.apple.com/account/resources/devices/list"
step "If '$DEVICE_NAME' is already listed with that UDID, skip ahead."
step "Otherwise: + (top left) → Platform 'iOS, tvOS, watchOS' →"
step "  Device Name 'iPhone 15 Pro' → Device ID (UDID) $DEVICE_UDID →"
step "  Continue → Register."
confirm "Is the device registered on the team?" || {
  SKIPPED+=("register device $DEVICE_UDID at developer.apple.com/account/resources/devices/list")
}
write_env DEVICE_UDID "$DEVICE_UDID"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Create the CloudKit container — do this BEFORE the bundle id"
say "The identifier page lets you tick an existing container but is a clumsy"
say "place to create one, so create it first and just select it in stage 4."
say ""
step "Container: $CONTAINER_ID"
say ""
warn "This is permanent. Apple: a container 'can't be deleted or renamed'."
say "The name is deliberately NOT tied to the working title 'Eczema Diary'"
say "(#697) — the app can be renamed later; this string cannot."
say ""
open_url "https://developer.apple.com/account/resources/identifiers/list/cloudContainer"
step "+ → iCloud Containers → Continue."
step "Description: 'Eczema Diary' (free text, editable, not the identifier)."
step "Identifier: $CONTAINER_ID"
step "Continue → Register."
confirm "Does the container $CONTAINER_ID exist?" || {
  SKIPPED+=("create CloudKit container $CONTAINER_ID")
}
write_env CLOUDKIT_CONTAINER "$CONTAINER_ID"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Register the App ID and its capabilities"
say "Capabilities here are not preference — two map decisions force them:"
step "#705 — sync is mandatory, no toggle. iCloud + CloudKit is required."
step "#714 — every encryptable field is encrypted, permanently."
step "      Mirroring arrives on silent pushes, so Push Notifications too."
say ""
warn "The bundle id is permanent once used. It is $BUNDLE_ID (#697),"
say "deliberately two segments, not reverse-DNS."
say ""
open_url "https://developer.apple.com/account/resources/identifiers/list/bundleId"
step "+ → App IDs → Continue → App → Continue."
step "Description: Eczema Diary"
step "Bundle ID: select Explicit, enter $BUNDLE_ID"
step "Under Capabilities tick: iCloud (choose 'Include CloudKit support'),"
step "  then Push Notifications."
step "In the iCloud row, use Configure / Edit and tick $CONTAINER_ID."
step "Continue → Register. Then reopen the identifier and confirm the"
step "  container is actually checked — the selection is easy to lose."
confirm "Is $BUNDLE_ID registered with iCloud+CloudKit, Push, and the container ticked?" || {
  SKIPPED+=("register App ID $BUNDLE_ID with iCloud/CloudKit + Push and container $CONTAINER_ID")
}
write_env BUNDLE_ID "$BUNDLE_ID"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify the container in the CloudKit console"
say "A container can exist on the identifiers page and still be unusable if"
say "no environment was provisioned. This is a read-only look."
open_url "https://icloud.developer.apple.com/dashboard/"
step "Pick $CONTAINER_ID from the container list."
step "Confirm a Development environment is present (Schema → Record Types)."
step "Do NOT promote anything to Production — schema promotion is a hard"
step "  deadline on other tickets (#714, #762) and is not this ticket's job."
confirm "Is the container visible with a Development environment?" || {
  SKIPPED+=("verify $CONTAINER_ID in the CloudKit console")
}

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Entitlements the scaffolding ticket will write"
say "Recorded here so the project-scaffolding ticket copies rather than"
say "re-derives them. Nothing to click — this is the handoff payload."
say ""
step "com.apple.developer.icloud-services = [ CloudKit ]"
step "com.apple.developer.icloud-container-identifiers = [ $CONTAINER_ID ]"
step "com.apple.developer.aps-environment = development"
step "UIBackgroundModes = [ remote-notification ]"
say ""
say "Not added, deliberately:"
step "No keychain-sharing group — #763 puts the photo key in this app's own"
step "  keychain item (kSecAttrSynchronizable, AfterFirstUnlock). Syncing an"
step "  item needs no sharing entitlement."
step "No App Groups, no distribution profile: development only (#768)."
pause "Noted?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Write the record into eczema-ios"
say "The record goes in eczema-ios so scaffolding can read it. #699 forbids"
say "secrets in the repo, and CI builds with CODE_SIGNING_ALLOWED=NO, so the"
say "committed file holds identifiers only — never keys, never a .p12."
say ""
step "File: $RECORD"
step "The Team ID and device UDID stay OUT of it (.gitignore blocks the"
step "  env file that holds them: $ENV_FILE)."
say ""
say "The agent that ran this wizard drafts the file and opens the PR; this"
say "stage exists so you can confirm the values above are final first."
confirm "Are all values above final, ready to be written up?" || {
  SKIPPED+=("re-run this wizard once the portal work is finished, then draft $RECORD")
}

finish
